export const TopVaults = [
  {
    id: '1',
    VaultName: 'Strategy 1',
    NFTAvatar: '/assets/1x1.png',
    creator: 'John',
    CreationTime: '2024-03-31',
  },
  {
    id: '2',
    VaultName: 'Strategy 2',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Jacky',
    CreationTime: '2024-03-31',
  },
  {
    id: '3',
    VaultName: 'Strategy 3',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Bob',
    CreationTime: '2024-03-31',
  },
  {
    id: '4',
    VaultName: 'Strategy 4',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Penny',
    CreationTime: '2024-03-31',
  },
];

export const Vaults = [
  {
    id: '1',
    VaultName: 'Strategy 1',
    NFTAvatar: '/assets/1x1.png',
    creator: 'John',
    CreationTime: '2024-03-31',
  },
  {
    id: '2',
    VaultName: 'Strategy 2',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Jacky',
    CreationTime: '2024-03-31',
  },
  {
    id: '3',
    VaultName: 'Strategy 3',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Bob',
    CreationTime: '2024-03-31',
  },
  {
    id: '4',
    VaultName: 'Strategy 4',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Penny',
    CreationTime: '2024-03-31',
  },
  {
    id: '5',
    VaultName: 'Strategy 5',
    NFTAvatar: '/assets/1x1.png',
    creator: 'John',
    CreationTime: '2024-03-31',
  },
  {
    id: '6',
    VaultName: 'Strategy 6',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Jacky',
    CreationTime: '2024-03-31',
  },
  {
    id: '7',
    VaultName: 'Strategy 7',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Bob',
    CreationTime: '2024-03-31',
  },
  {
    id: '8',
    VaultName: 'Strategy 8',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Penny',
    CreationTime: '2024-03-31',
  },
  {
    id: '9',
    VaultName: 'Strategy 9',
    NFTAvatar: '/assets/1x1.png',
    creator: 'John',
    CreationTime: '2024-03-31',
  },
  {
    id: '10',
    VaultName: 'Strategy 10',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Jacky',
    CreationTime: '2024-03-31',
  },
  {
    id: '11',
    VaultName: 'Strategy 11',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Bob',
    CreationTime: '2024-03-31',
  },
  {
    id: '12',
    VaultName: 'Strategy 12',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Penny',
    CreationTime: '2024-03-31',
  },
  {
    id: '13',
    VaultName: 'Strategy 13',
    NFTAvatar: '/assets/1x1.png',
    creator: 'John',
    CreationTime: '2024-03-31',
  },
  {
    id: '14',
    VaultName: 'Strategy 14',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Jacky',
    CreationTime: '2024-03-31',
  },
  {
    id: '15',
    VaultName: 'Strategy 15',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Bob',
    CreationTime: '2024-03-31',
  },
  {
    id: '16',
    VaultName: 'Strategy 16',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Penny',
    CreationTime: '2024-03-31',
  },
  {
    id: '17',
    VaultName: 'Strategy 17',
    NFTAvatar: '/assets/1x1.png',
    creator: 'John',
    CreationTime: '2024-03-31',
  },
  {
    id: '18',
    VaultName: 'Strategy 18',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Jacky',
    CreationTime: '2024-03-31',
  },
  {
    id: '19',
    VaultName: 'Strategy 19',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Bob',
    CreationTime: '2024-03-31',
  },
  {
    id: '20',
    VaultName: 'Strategy 20',
    NFTAvatar: '/assets/1x1.png',
    creator: 'Penny',
    CreationTime: '2024-03-31',
  },
];
